name: fact_proj
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - pip=23.3.1
  - numpy=*
  - torchvision=*
  - pandas=*
  - pytorchcv=*
  - pip:
    - torch=*
    - tqdm=*
