name: fact_proj
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11.5
  - pip=23.3.1
  - torchvision=0.16.0
  - pip:
    - pytorchcv>=0.0.67
    - pandas>=2.1.4
    - numpy>=1.19.5
    - torch>=2.1.2
    - tqdm>=4.66.1
