name: fact_proj
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11.5
  - pip=23.3.1
  - torchvision
  - pip:
    - pytorchcv
    - pandas
    - numpy
    - torch
    - tqdm
    - scikit-learn
    - argparse
