#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --job-name=InstallEnv
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=04:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out

module purge
module load 2023
module load Python/3.11.3-GCCcore-12.3.0

# check available environments
conda info --envs

# create the environment
pipenv install

# verify installation
conda info --envs