#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=9
#SBATCH --gpus=1
#SBATCH --job-name=RunPaper
#SBATCH --ntasks=1
#SBATCH --time=02:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out

module purge
module load 2023
module load Python/3.11.3-GCCcore-12.3.0

# Activate your environment
pipenv shell

python -c "import torch; print(torch.__version__)"

srun python -c "import torch; print(torch.__version__)"
